_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en-gb
uuid: 1dabb71d-438f-4485-9388-542e5a77ca7f
name: test
mail: test@mail.com
slogan: 'value=Offer platform'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
